<a href="https://colab.research.google.com/github/Jess-chege/Data-Science-projects/blob/main/Numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Write a NumPy program to test element-wise for NaN of a given array.
#Nan elements are the missing elements represented as NaN meaning not numbers in an array

import numpy as np

# Create an array with some NaN values
array = np.array([1, 3, np.nan, 7, np.nan, 10])

# Test element-wise for NaN
results = np.isnan(array)

print("Original Array:")
print(array)

print("\nElement-wise NaN test:")
print(results)

Original Array:
[ 1.  3. nan  7. nan 10.]

Element-wise NaN test:
[False False  True False  True False]

In [ ]:
#Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
#complex number: 1.0 + 2.0j, 1.5 + 2.5j
#real number: -3, -7.2
#scalar types: single value type in the array
import numpy as np
#an array that contains both complex and real numbers
arr = np.array([1.0 + 2.0j, 5])

#Test element-wise for complex numbers
is_complex = np.iscomplex(arr)

#Test element-wise for real numbers
is_real = np.isreal(arr)
#testing if a given number is scalar
x = 30
is_x_scalar = np.isscalar(x)

print("Original Array:")
print(arr)
#testing if the elements in the array are complex
print("\nElement-wise complex number test:")
print(is_complex)
#testing if the elements in the array are real numbers
print("\nElement-wise real number test:")
print(is_real)
#checking if the element in array x is scalar
print(f"\nIs {x} a scalar? →", is_x_scalar)

Original Array:
[1.+2.j 5.+0.j]

Element-wise complex number test:
[ True False]

Element-wise real number test:
[False  True]

Is 30 a scalar? → True

In [ ]:
#Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
import numpy as np

# Create two arrays
arr1 = np.array([1.0, 3.003, 4.0005, 5.0])
arr2 = np.array([1.0, 3.009, 4.0004, 5.1])

# Test element-wise equality within a tolerance
# absolutetol = absolute tolerance, relativetol = relative tolerance
result = np.isclose(arr1, arr2, rtol=1e-03, atol=1e-05)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("\nAre they element-wise equal within tolerance?")
print(result)

Array 1: [1.     3.003  4.0005 5.    ]
Array 2: [1.     3.009  4.0004 5.1   ]

Are they element-wise equal within tolerance?
[ True False  True False]

In [ ]:
#Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
#creating the two arrays
arr1 = np.array([2, 3, 143, 5, 6, 7])
arr2 = np.array([12, 23, 34, 55, 16, 18])

#printing the arrays
print(arr1)
print(type(arr1))
print(arr2)
print(type(arr2))

#comparing the two arrays using different functions
result1 = np.greater(arr1 , arr2)
print(result1)

result2 = np.greater_equal(arr1, arr2)
print(result2)

result3 = np.less(arr1, arr2)
print(result3)

result4 = np.less_equal(arr1,arr2)
print(result4)

[  2   3 143   5   6   7]
<class 'numpy.ndarray'>
[12 23 34 55 16 18]
<class 'numpy.ndarray'>
[False False  True False False False]
[False False  True False False False]
[ True  True False  True  True  True]
[ True  True False  True  True  True]

In [ ]:
#Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
#creating the two arrays
import numpy as np

# Create two arrays
arr1 = np.array([1.0, 2.0001, 3.0, 4.5])
arr2 = np.array([1.0, 2.0002, 3.5, 4.5])

# Element-wise comparison for exact equality
exact_equal = np.equal(arr1, arr2)

# Element-wise comparison within a tolerance
#relative tolerance and the absolute tolerance
tolerance_equal = np.isclose(arr1, arr2, rtol=1e-03, atol=1e-05)

print("Array 1:", arr1)
print("Array 2:", arr2)

print("\nElement-wise exact equality:")
print(exact_equal)

print("\nElement-wise equality within tolerance:")
print(tolerance_equal)

Array 1: [1.     2.0001 3.     4.5   ]
Array 2: [1.     2.0002 3.5    4.5   ]

Element-wise exact equality:
[ True False False  True]

Element-wise equality within tolerance:
[ True  True False  True]

In [ ]:
#Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
array1 =np.array([1, 7, 13, 105])

#printing the original array
print(array1)

# Calculating the size of the memory occupied by the array 'x' (number of elements multiplied by the size of each element in bytes) and printing the result
print("Size of the memory occupied by the array:")
print("%d bytes" % (array1.size * array1.itemsize))

[  1   7  13 105]
Size of the memory occupied by the array:
32 bytes

#In the code cell below, write the code to get and display the 55th row in the dataframe df.
#using the iloc function to select a specfic row taking into account that in python indexing starts at 0
#df.iloc[54]

#In the code cell below write the code to display the first 10 rows of the dataframe df.
#using the head(10) to display the first 10 rows in a dataset
#df.head(10)

In [ ]:
#In the code cell below, select and display the first eight rows from the 'Country' and 'TB deaths' columns.
#importing pandas
import pandas as pd

#importing the Country dataset
Country_df = pd.read_csv("/content/drive/MyDrive/datasets/Delhi_DEL_2014.csv")
Country_df.head(8)

,Date,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,-4,-7,-9,-9,-10,-11,82,70,58,...,2,2,2,6,2,NaN,0.0,8.0,NaN,-1<br />
1,2014-1-2,-1,-4,-8,-6,-8,-11,75,69,53,...,3,2,2,6,0,NaN,0.0,8.0,NaN,-1<br />
2,2014-1-3,1,-3,-8,-4,-6,-10,84,72,54,...,3,2,2,6,0,NaN,0.0,8.0,NaN,-1<br />
3,2014-1-4,-1,-2,-3,-4,-5,-6,80,74,64,...,8,4,2,14,2,NaN,0.0,8.0,NaN,-1<br />
4,2014-1-5,-1,-3,-6,-4,-6,-8,93,79,71,...,6,3,2,14,2,NaN,0.0,8.0,Snow,-1<br />
5,2014-1-6,-2,-4,-9,-7,-9,-12,80,67,45,...,10,6,3,14,3,NaN,0.0,8.0,NaN,-1<br />
6,2014-1-7,-4,-7,-9,-10,-11,-12,86,72,48,...,10,6,2,14,6,NaN,0.0,7.0,Snow,30<br />
7,2014-1-8,-5,-7,-11,-9,-10,-12,87,75,65,...,6,4,2,11,5,NaN,0.0,8.0,NaN,-1<br />

In [ ]:
#importing the TB dataset
tb_df = pd.read_csv("/content/drive/MyDrive/datasets/WHO POP TB all.csv")
tb_df.head(8)

               Country  Population (1000s)  TB deaths
0          Afghanistan               30552   13000.00
1              Albania                3173      20.00
2              Algeria               39208    5100.00
3              Andorra                  79       0.26
4               Angola               21472    6900.00
5  Antigua and Barbuda                  90       1.20
6            Argentina               41446     570.00
7              Armenia                2977     170.00

In [ ]:
#In the code cell below write code to find all the rows in df where TB deaths exceed 10000.
# Find all rows where TB deaths exceed 10000
high_tb_deaths = tb_df[tb_df['TB deaths'] > 10000]
print(high_tb_deaths)
print(high_tb_deaths.sum())

                              Country  Population (1000s)  TB deaths
0                         Afghanistan               30552    13000.0
13                         Bangladesh              156595    80000.0
36                              China             1393337    41000.0
47   Democratic Republic of the Congo               67514    46000.0
58                           Ethiopia               94101    30000.0
77                              India             1252140   240000.0
78                          Indonesia              249866    64000.0
100                        Madagascar               22925    12000.0
115                        Mozambique               25834    18000.0
116                           Myanmar               53259    26000.0
124                           Nigeria              173615   160000.0
128                          Pakistan              182143    49000.0
134                       Philippines               98394    27000.0
141                Russian Federation              142834    17000.0
159                      South Africa               52776    25000.0
190                          Viet Nam               91680    17000.0
Country               AfghanistanBangladeshChinaDemocratic Republic ...
Population (1000s)                                              4087565
TB deaths                                                      865000.0
dtype: object

In [ ]:
#In the code cell below find all the countries where the Population (1000s) is less than or equal to 50000 or TB deaths are greater than or equal to 20000.
#displaying the countries where Population(1000s) is less than or equal to 50000 or tb deaths are greater than or equal to 20000
high_tb_deaths_countries = tb_df[
    (tb_df['Population (1000s)'] <= 50000) |
    (tb_df['TB deaths'] >= 20000)]
#printing the results
print(high_tb_deaths_countries)
print(high_tb_deaths_countries.sum())

                                Country  Population (1000s)  TB deaths
0                           Afghanistan               30552   13000.00
1                               Albania                3173      20.00
2                               Algeria               39208    5100.00
3                               Andorra                  79       0.26
4                                Angola               21472    6900.00
..                                  ...                 ...        ...
188                             Vanuatu                 253      16.00
189  Venezuela (Bolivarian Republic of)               30405     480.00
191                               Yemen               24407     990.00
192                              Zambia               14539    3600.00
193                            Zimbabwe               14150    5700.00

[180 rows x 3 columns]
Country               AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...
Population (1000s)                                              5549106
TB deaths                                                    1016737.97
dtype: object

Assignment

In [ ]:
#Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_df =pd.Series(arr)
print(arr_df)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#Write a Python program to convert a Panda module Series to Python list and it's type.
#creating the pandas series
df_series = pd.Series([1,2,3,4,5])
#converting the pandas series to a python list
my_list = df_series.tolist()
# Display the list and its type
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>

In [ ]:
#Write a Python program to add, subtract, multiple and divide two Pandas Series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]
#creating the two pandas series
df1 = pd.Series([2, 4, 6, 8, 10])
df2 = pd.Series([1, 3, 5, 7, 9])

# Performing arithmetic operations
print("\nAddition:")
print(df1 + df2)

print("\nSubtraction:")
print(df1 - df2)

print("\nMultiplication:")
print(df1 * df2)

print("\nDivision:")
print(df1 / df2)

Addition:
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtraction:
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiplication:
0     2
1    12
2    30
3    56
4    90
dtype: int64

Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [ ]:
#Write a Python program to get the largest integer smaller or equal to the division of the inputs. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]
data1 =pd.Series([2, 4, 6, 8, 10])
data2 =pd.Series([1, 3, 5, 7, 9])
#division of the two sample series
data3 =data1/data2
print(data3)
#showing the larger integer
data3.max()

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

2.0

In [ ]:
#showing the smaller integer
data3.min()

1.1111111111111112

In [ ]:
#Write a Python program to convert a dictionary to a Pandas series. Sample Series: Original dictionary: {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800} Converted series: a 100 b 200 c 300 d 400 e 800 dtype: int64
#input
my_dict =  {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
#Converting the dictionary to a pandas series
data_series = pd.Series(my_dict)
#printing the created data series
print(data_series)

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [ ]:
#Write a Python program to convert a NumPy array to a Pandas series. Sample Series: NumPy array: [10 20 30 40 50] Converted Pandas series: 0 10 1 20 2 30 3 40 4 50 dtype: int64
#input in numpy array
arr =np.array([10, 20, 30, 40, 50])

#converting numpy array to pandas serires
series1 = pd.Series(arr)

#displaying the pandas series
print(series1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#Write a Python program to change the data type of given a column or a Series. Sample Series: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Change the said data type to numeric: 0 100.00 1 200.00 2 NaN 3 300.12 4 400.00 dtype: float64

sample_series = pd.Series([0, 100, 1, 200, 2, 'python', 3, 300.12, 4, 400])
print("Original Data Series:")
print(sample_series)

# Changing the data type to numeric
numeric_data = pd.to_numeric(sample_series, errors='coerce')

print("\nChange the said data type to numeric:")
print(numeric_data)

Original Data Series:
0         0
1       100
2         1
3       200
4         2
5    python
6         3
7    300.12
8         4
9       400
dtype: object

Change the said data type to numeric:
0      0.00
1    100.00
2      1.00
3    200.00
4      2.00
5       NaN
6      3.00
7    300.12
8      4.00
9    400.00
dtype: float64

In [ ]:
#Write a Python Pandas program to convert the first column of a DataFrame as a Series. Sample Output: Original DataFrame col1 col2 col3 0 1 4 7 1 2 5 5 2 3 6 8 3 4 9 12 4 7 5 1 5 11 0 11 1st column as a Series: 0 1 1 2 2 3 3 4 4 7 5 11 Name: col1, dtype: int64 <class 'pandas.core.series.Series'>
data = {
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Converting the first column (col1) to a Series
first_col_series = df.iloc[:, 0]

print("\n1st column as a Series:")
print(first_col_series)
print(type(first_col_series))

Original DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
#Write a Pandas program to convert a given Series to an array. Sample Output: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Series to an array ['100' '200' 'python' '300.12' '400']
data4 = pd.Series([100, 200, 'python', 300.12, 400])
print("Original Data Series:")
print(data4)

# Convert Series to a NumPy array
array_data = data4.to_numpy()

print("\nSeries to an array:")
print(array_data)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array:
[100 200 'python' 300.12 400]

In [ ]:
#Write a Pandas program to convert Series of lists to one Series. Sample Output: Original Series of list 0 [Red, Green, White] 1 [Red, Black] 2 [Yellow] dtype: object One Series 0 Red 1 Green 2 White 3 Red 4 Black 5 Yellow dtype: object
# Original Series of lists
data5 = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])

print("Original Series of list:")
print(data5)

# Convert Series of lists to one flattened Series
flattened = data5.explode().reset_index(drop=True)

print("\nOne Series:")
print(flattened)

Original Series of list:
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [ ]:
#Write a Pandas program to sort a given Series. Sample Output: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object 0 100 1 200 3 300.12 4 400 2 python dtype: object
# Original Data Series
data = pd.Series([100, 200, 'python', 300.12, 400])
print("Original Data Series:")
print(data)

# Convert all values to strings before sorting
sorted_data = data.astype(str).sort_values(ignore_index=True)

print("\nSorted Data Series:")
print(sorted_data)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted Data Series:
0       100
1       200
2    300.12
3       400
4    python
dtype: object

In [ ]:
#Write a Pandas program to add some data to an existing Series. Sample Output: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Data Series after adding some data: 0 100 1 200 2 python 3 300.12 4 400 0 500 1 php dtype: object
# Original Data Series
data7 = pd.Series([100, 200, 'python', 300.12, 400])
print("Original Data Series:")
print(data7)

# creating new data to be added
new_data = pd.Series([500, 'php'])

# Add using the concat function the new data to the existing Series
updated_data = pd.concat([data7, new_data], ignore_index=True)

print("\nData Series after adding some data:")
print(updated_data)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

Assessment
See the attached datasets in Data Analysis folder  Beijing_PEK_2014.csv, Brasilia_BSB_2014.csv, CapeTown_CPT_2014.csv, Delhi_DEL_2014.csv, London_2014.csv, and Moscow_SVO_2014.csv. Explore them, run your analysis on them, and detail your findings below as much as you can.

In [ ]:
#importing the datasets
data_beijing = pd.read_csv('/content/drive/MyDrive/datasets/Beijing_PEK_2014.csv')
data_beijing.head(10)

,Date,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,12,4,-2,-12,-17,-20,44,19,7,...,31,11,5,32,16,47.0,0.0,NaN,NaN,291<br />
1,2014-1-2,7,0,-6,-6,-9,-13,74,50,28,...,18,7,3,18,5,NaN,0.0,NaN,NaN,20<br />
2,2014-1-3,9,3,-2,-7,-13,-18,64,32,9,...,31,13,5,18,8,NaN,0.0,NaN,NaN,24<br />
3,2014-1-4,2,-2,-6,-4,-7,-9,80,68,44,...,10,5,2,11,5,NaN,0.0,2.0,NaN,56<br />
4,2014-1-5,7,0,-7,-5,-11,-15,80,51,15,...,31,7,3,18,10,NaN,0.0,NaN,NaN,18<br />
5,2014-1-6,0,-2,-3,-4,-5,-7,80,72,61,...,5,3,2,14,5,NaN,0.0,8.0,Snow,130<br />
6,2014-1-7,5,0,-5,-4,-12,-25,86,45,6,...,31,6,2,18,8,NaN,0.0,8.0,NaN,7<br />
7,2014-1-8,1,-4,-8,-20,-23,-28,36,21,6,...,31,30,26,32,14,47.0,0.0,NaN,NaN,344<br />
8,2014-1-9,1,-6,-12,-21,-26,-35,41,19,4,...,31,24,10,26,11,43.0,0.0,NaN,NaN,321<br />
9,2014-1-10,5,-4,-13,-18,-23,-29,48,25,5,...,23,12,5,21,6,47.0,0.0,NaN,NaN,349<br />

In [ ]:
#Getting the data information using the data.info()function to understand the first dtaset
data_beijing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    object
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            365 non-null    int64
 14   Mean VisibilityKm           365 non-null    int64
 15   Min VisibilitykM            365 non-null    int64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          154 non-null    float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  141 non-null    float64
 21   Events                      122 non-null    object
 22  WindDirDegrees<br />         365 non-null    object
dtypes: float64(3), int64(17), object(3)
memory usage: 65.7+ KB

In [ ]:
#checking for the null values in the datasets
data_beijing.isnull().sum()

Date                             0
Max TemperatureC                 0
Mean TemperatureC                0
Min TemperatureC                 0
Dew PointC                       0
MeanDew PointC                   0
Min DewpointC                    0
Max Humidity                     0
 Mean Humidity                   0
 Min Humidity                    0
 Max Sea Level PressurehPa       0
 Mean Sea Level PressurehPa      0
 Min Sea Level PressurehPa       0
 Max VisibilityKm                0
 Mean VisibilityKm               0
 Min VisibilitykM                0
 Max Wind SpeedKm/h              0
 Mean Wind SpeedKm/h             0
 Max Gust SpeedKm/h            211
Precipitationmm                  0
 CloudCover                    224
 Events                        243
WindDirDegrees<br />             0
dtype: int64

In [ ]:
#using a combination of forward fill and the backward fill to fill the null values
beijing = data_beijing.ffill().bfill()
beijing.isna().sum()

Date                           0
Max TemperatureC               0
Mean TemperatureC              0
Min TemperatureC               0
Dew PointC                     0
MeanDew PointC                 0
Min DewpointC                  0
Max Humidity                   0
 Mean Humidity                 0
 Min Humidity                  0
 Max Sea Level PressurehPa     0
 Mean Sea Level PressurehPa    0
 Min Sea Level PressurehPa     0
 Max VisibilityKm              0
 Mean VisibilityKm             0
 Min VisibilitykM              0
 Max Wind SpeedKm/h            0
 Mean Wind SpeedKm/h           0
 Max Gust SpeedKm/h            0
Precipitationmm                0
 CloudCover                    0
 Events                        0
WindDirDegrees<br />           0
dtype: int64

In [ ]:
#claculating the statistical description
beijing.describe()

,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,Max Sea Level PressurehPa,Mean Sea Level PressurehPa,Min Sea Level PressurehPa,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,19.523288,13.364384,7.542466,6.580822,2.123288,-2.465753,78.630137,50.753425,23.753425,1019.536986,1016.657534,1013.934247,18.073973,9.504110,4.131507,21.961644,8.942466,40.035616,1.112027,6.213699
std,11.249060,10.937703,11.032742,12.328479,13.762452,15.056015,18.203299,19.083953,17.474142,10.026442,9.641969,9.512055,10.124907,6.458074,3.993019,10.709894,4.651536,12.518178,5.510722,2.497984
min,-2.000000,-7.000000,-13.000000,-24.000000,-33.000000,-40.000000,19.000000,8.000000,4.000000,1001.000000,996.000000,993.000000,2.000000,1.000000,0.000000,6.000000,3.000000,21.000000,0.000000,1.000000
25%,9.000000,3.000000,-3.000000,-4.000000,-9.000000,-14.000000,69.000000,37.000000,8.000000,1010.000000,1008.000000,1005.000000,8.000000,5.000000,2.000000,14.000000,6.000000,32.000000,0.000000,4.000000
50%,22.000000,14.000000,9.000000,9.000000,3.000000,-2.000000,83.000000,50.000000,20.000000,1019.000000,1016.000000,1014.000000,18.000000,7.000000,3.000000,18.000000,8.000000,35.000000,0.000000,8.000000
75%,30.000000,23.000000,18.000000,18.000000,15.000000,11.000000,94.000000,65.000000,36.000000,1028.000000,1025.000000,1022.000000,31.000000,13.000000,6.000000,26.000000,10.000000,47.000000,0.000000,8.000000
max,42.000000,31.000000,27.000000,25.000000,24.000000,23.000000,100.000000,93.000000,81.000000,1039.000000,1037.000000,1034.000000,31.000000,31.000000,31.000000,72.000000,34.000000,93.000000,75.950000,8.000000

In [ ]:
print("\n=== Summary Observation ===")
print(f"The Beijing dataset contains {beijing.shape[0]} daily records and {beijing.shape[1]} columns.")
print("Forward fill and backward fill were used to handle missing values.")
print("The dataset is now complete and ready for analysis.")

=== Summary Observation ===
The Beijing dataset contains 365 daily records and 23 columns.
Forward fill and backward fill were used to handle missing values.
The dataset is now complete and ready for analysis.

In [ ]:
#importing dataset  Brasilia_BSB_2014
brasilia = pd.read_csv('/content/drive/MyDrive/datasets/Brasilia_BSB_2014.csv')
brasilia.head(10)

,Date,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,31,24,17,19,18,16,94,64,33,...,19,11,10,14,5,NaN,0.00,3.0,Thunderstorm,125<br />
1,2014-1-2,30,23,17,19,17,14,94,65,33,...,19,12,10,16,5,NaN,0.00,2.0,NaN,102<br />
2,2014-1-3,32,24,18,20,15,11,88,55,19,...,19,13,10,19,6,NaN,0.00,2.0,NaN,133<br />
3,2014-1-4,32,25,18,17,13,8,77,47,16,...,19,12,10,24,6,NaN,0.00,2.0,NaN,106<br />
4,2014-1-5,30,24,19,16,13,9,83,48,23,...,19,12,10,24,8,NaN,0.00,3.0,Rain,106<br />
5,2014-1-6,30,24,18,19,16,11,94,62,20,...,19,11,10,19,5,NaN,1.02,3.0,Thunderstorm,14<br />
6,2014-1-7,29,23,18,17,15,12,88,58,27,...,19,11,10,24,6,NaN,0.00,2.0,Thunderstorm,85<br />
7,2014-1-8,29,22,15,15,13,10,88,55,22,...,19,12,10,19,8,NaN,0.00,2.0,NaN,115<br />
8,2014-1-9,29,24,18,16,13,10,73,50,29,...,19,11,10,21,8,NaN,0.00,3.0,NaN,110<br />
9,2014-1-10,28,24,19,16,15,13,73,55,34,...,19,12,10,23,10,NaN,0.00,3.0,Thunderstorm,94<br />

In [ ]:
#checking the data infor
brasilia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    object
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            365 non-null    int64
 14   Mean VisibilityKm           365 non-null    int64
 15   Min VisibilitykM            365 non-null    int64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          36 non-null     float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  334 non-null    float64
 21   Events                      162 non-null    object
 22  WindDirDegrees<br />         365 non-null    object
dtypes: float64(3), int64(17), object(3)
memory usage: 65.7+ KB

In [ ]:
#checking for the null values in the datasets
brasilia.isnull().sum()

Date                             0
Max TemperatureC                 0
Mean TemperatureC                0
Min TemperatureC                 0
Dew PointC                       0
MeanDew PointC                   0
Min DewpointC                    0
Max Humidity                     0
 Mean Humidity                   0
 Min Humidity                    0
 Max Sea Level PressurehPa       0
 Mean Sea Level PressurehPa      0
 Min Sea Level PressurehPa       0
 Max VisibilityKm                0
 Mean VisibilityKm               0
 Min VisibilitykM                0
 Max Wind SpeedKm/h              0
 Mean Wind SpeedKm/h             0
 Max Gust SpeedKm/h            329
Precipitationmm                  0
 CloudCover                     31
 Events                        203
WindDirDegrees<br />             0
dtype: int64

In [ ]:
brasilia_data = brasilia.ffill().bfill()
brasilia_data.isna().sum()

Date                           0
Max TemperatureC               0
Mean TemperatureC              0
Min TemperatureC               0
Dew PointC                     0
MeanDew PointC                 0
Min DewpointC                  0
Max Humidity                   0
 Mean Humidity                 0
 Min Humidity                  0
 Max Sea Level PressurehPa     0
 Mean Sea Level PressurehPa    0
 Min Sea Level PressurehPa     0
 Max VisibilityKm              0
 Mean VisibilityKm             0
 Min VisibilitykM              0
 Max Wind SpeedKm/h            0
 Mean Wind SpeedKm/h           0
 Max Gust SpeedKm/h            0
Precipitationmm                0
 CloudCover                    0
 Events                        0
WindDirDegrees<br />           0
dtype: int64

In [ ]:
#calculating the statistical data
brasilia_data.describe()

,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,Max Sea Level PressurehPa,Mean Sea Level PressurehPa,Min Sea Level PressurehPa,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,28.284932,22.895890,17.726027,15.813699,13.676712,10.558904,79.504110,58.068493,29.780822,1021.410959,1019.219178,1017.016438,18.975342,12.265753,8.780822,22.364384,7.632877,42.175342,2.059315,3.372603
std,2.324243,2.035431,2.702564,3.496203,3.896974,4.949188,11.356758,13.868821,14.187952,2.347758,2.333738,2.523462,0.471082,2.459128,4.389193,11.227730,2.659632,8.172383,6.186198,1.403808
min,19.000000,16.000000,9.000000,6.000000,3.000000,-5.000000,47.000000,26.000000,6.000000,1015.000000,1014.000000,1012.000000,10.000000,7.000000,0.000000,10.000000,3.000000,26.000000,0.000000,1.000000
25%,27.000000,21.000000,16.000000,13.000000,11.000000,7.000000,73.000000,49.000000,19.000000,1020.000000,1018.000000,1015.000000,19.000000,11.000000,6.000000,19.000000,6.000000,35.000000,0.000000,2.000000
50%,28.000000,23.000000,18.000000,17.000000,14.000000,11.000000,83.000000,58.000000,27.000000,1021.000000,1019.000000,1017.000000,19.000000,12.000000,10.000000,21.000000,8.000000,40.000000,0.000000,3.000000
75%,29.000000,24.000000,20.000000,19.000000,17.000000,15.000000,88.000000,70.000000,39.000000,1023.000000,1020.000000,1018.000000,19.000000,13.000000,10.000000,24.000000,10.000000,47.000000,0.760000,5.000000
max,36.000000,28.000000,23.000000,22.000000,19.000000,18.000000,100.000000,88.000000,73.000000,1028.000000,1026.000000,1025.000000,19.000000,19.000000,19.000000,195.000000,19.000000,66.000000,57.910000,7.000000

In [ ]:
#importing dataset CapeTown_CPT_2014.csv,
capetown = pd.read_csv('/content/drive/MyDrive/datasets/CapeTown_CPT_2014.csv')
capetown.head(10)

,Date,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,28,23,18,19,17,15,88,71,45,...,19.0,14.0,10.0,35,14,NaN,0.00,2.0,NaN,213<br />
1,2014-1-2,28,23,18,19,18,16,88,74,46,...,26.0,13.0,10.0,32,21,NaN,0.00,2.0,NaN,204<br />
2,2014-1-3,27,23,19,19,18,18,94,75,48,...,31.0,12.0,3.0,32,26,NaN,0.00,4.0,NaN,193<br />
3,2014-1-4,27,22,18,19,18,14,88,74,46,...,26.0,13.0,9.0,32,18,NaN,0.00,3.0,NaN,314<br />
4,2014-1-5,26,22,18,17,16,14,83,70,46,...,26.0,13.0,10.0,45,21,NaN,0.00,4.0,Rain,25<br />
5,2014-1-6,26,22,18,19,16,14,94,78,61,...,26.0,11.0,4.0,42,18,NaN,6.10,6.0,Rain,171<br />
6,2014-1-7,24,21,18,18,17,16,88,77,59,...,31.0,12.0,10.0,45,29,NaN,2.03,4.0,Rain,162<br />
7,2014-1-8,24,21,18,18,17,16,94,82,62,...,19.0,10.0,0.0,29,16,47.0,0.00,5.0,Fog-Rain,295<br />
8,2014-1-9,23,20,16,16,15,14,88,75,48,...,31.0,12.0,6.0,40,19,NaN,5.08,4.0,Rain,326<br />
9,2014-1-10,23,20,16,16,13,12,88,65,40,...,31.0,11.0,10.0,37,24,NaN,0.00,2.0,Rain,180<br />

In [ ]:
#checking the data info
capetown.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    object
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            363 non-null    float64
 14   Mean VisibilityKm           363 non-null    float64
 15   Min VisibilitykM            363 non-null    float64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          50 non-null     float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  310 non-null    float64
 21   Events                      136 non-null    object
 22  WindDirDegrees<br />         365 non-null    object
dtypes: float64(6), int64(14), object(3)
memory usage: 65.7+ KB

In [ ]:
#checking the dataset shape
capetown.shape

(365, 23)

In [ ]:
#checking null values
capetown.isna().sum()

Date                             0
Max TemperatureC                 0
Mean TemperatureC                0
Min TemperatureC                 0
Dew PointC                       0
MeanDew PointC                   0
Min DewpointC                    0
Max Humidity                     0
 Mean Humidity                   0
 Min Humidity                    0
 Max Sea Level PressurehPa       0
 Mean Sea Level PressurehPa      0
 Min Sea Level PressurehPa       0
 Max VisibilityKm                2
 Mean VisibilityKm               2
 Min VisibilitykM                2
 Max Wind SpeedKm/h              0
 Mean Wind SpeedKm/h             0
 Max Gust SpeedKm/h            315
Precipitationmm                  0
 CloudCover                     55
 Events                        229
WindDirDegrees<br />             0
dtype: int64

In [ ]:
print(capetown.columns.tolist())

['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']

In [ ]:
capetown.drop([' Max Gust SpeedKm/h'], axis=1, inplace=True)
capetown.head(10)

,Date,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Min Sea Level PressurehPa,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,28,23,18,19,17,15,88,71,45,...,1008,19.0,14.0,10.0,35,14,0.00,2.0,NaN,213<br />
1,2014-1-2,28,23,18,19,18,16,88,74,46,...,1009,26.0,13.0,10.0,32,21,0.00,2.0,NaN,204<br />
2,2014-1-3,27,23,19,19,18,18,94,75,48,...,1007,31.0,12.0,3.0,32,26,0.00,4.0,NaN,193<br />
3,2014-1-4,27,22,18,19,18,14,88,74,46,...,1005,26.0,13.0,9.0,32,18,0.00,3.0,NaN,314<br />
4,2014-1-5,26,22,18,17,16,14,83,70,46,...,1003,26.0,13.0,10.0,45,21,0.00,4.0,Rain,25<br />
5,2014-1-6,26,22,18,19,16,14,94,78,61,...,1007,26.0,11.0,4.0,42,18,6.10,6.0,Rain,171<br />
6,2014-1-7,24,21,18,18,17,16,88,77,59,...,1008,31.0,12.0,10.0,45,29,2.03,4.0,Rain,162<br />
7,2014-1-8,24,21,18,18,17,16,94,82,62,...,1008,19.0,10.0,0.0,29,16,0.00,5.0,Fog-Rain,295<br />
8,2014-1-9,23,20,16,16,15,14,88,75,48,...,1009,31.0,12.0,6.0,40,19,5.08,4.0,Rain,326<br />
9,2014-1-10,23,20,16,16,13,12,88,65,40,...,1014,31.0,11.0,10.0,37,24,0.00,2.0,Rain,180<br />

In [ ]:
#filling the missing values using ffill and bfill
capetown1 =capetown.ffill().bfill()
capetown1.isna().sum()

Date                           0
Max TemperatureC               0
Mean TemperatureC              0
Min TemperatureC               0
Dew PointC                     0
MeanDew PointC                 0
Min DewpointC                  0
Max Humidity                   0
 Mean Humidity                 0
 Min Humidity                  0
 Max Sea Level PressurehPa     0
 Mean Sea Level PressurehPa    0
 Min Sea Level PressurehPa     0
 Max VisibilityKm              0
 Mean VisibilityKm             0
 Min VisibilitykM              0
 Max Wind SpeedKm/h            0
 Mean Wind SpeedKm/h           0
Precipitationmm                0
 CloudCover                    0
 Events                        0
WindDirDegrees<br />           0
dtype: int64

In [ ]:
capetown1.describe()

,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,Max Sea Level PressurehPa,Mean Sea Level PressurehPa,Min Sea Level PressurehPa,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Precipitationmm,CloudCover
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,22.684932,17.567123,12.509589,13.783562,11.583562,9.134247,87.452055,68.758904,42.150685,1019.347945,1016.654795,1014.232877,27.279452,14.493151,8.706849,31.090411,16.934247,1.173288,3.008219
std,4.839957,4.148880,4.288118,3.018215,3.289469,3.892943,7.311817,8.740581,12.762918,5.428054,5.220549,5.284023,4.723537,4.398187,5.066490,10.294031,7.334703,4.503512,1.762690
min,11.000000,7.000000,1.000000,5.000000,2.000000,-2.000000,63.000000,42.000000,0.000000,1006.000000,1004.000000,1002.000000,10.000000,6.000000,0.000000,11.000000,5.000000,0.000000,1.000000
25%,19.000000,14.000000,9.000000,12.000000,9.000000,6.000000,82.000000,62.000000,34.000000,1016.000000,1013.000000,1010.000000,26.000000,12.000000,6.000000,23.000000,11.000000,0.000000,1.000000
50%,23.000000,18.000000,13.000000,14.000000,12.000000,9.000000,88.000000,69.000000,42.000000,1019.000000,1016.000000,1014.000000,31.000000,13.000000,10.000000,32.000000,16.000000,0.000000,3.000000
75%,26.000000,21.000000,16.000000,16.000000,14.000000,12.000000,94.000000,76.000000,50.000000,1022.000000,1020.000000,1017.000000,31.000000,16.000000,10.000000,39.000000,21.000000,0.000000,4.000000
max,37.000000,28.000000,22.000000,21.000000,20.000000,18.000000,100.000000,88.000000,78.000000,1036.000000,1034.000000,1033.000000,31.000000,31.000000,31.000000,58.000000,43.000000,59.940000,7.000000

In [ ]:
#importing dataset Delhi_DEL_2014.csv,
delhi = pd.read_csv('/content/drive/MyDrive/datasets/Delhi_DEL_2014.csv')
delhi.head(10)

,Date,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,-4,-7,-9,-9,-10,-11,82,70,58,...,2,2,2,6,2,NaN,0.0,8.0,NaN,-1<br />
1,2014-1-2,-1,-4,-8,-6,-8,-11,75,69,53,...,3,2,2,6,0,NaN,0.0,8.0,NaN,-1<br />
2,2014-1-3,1,-3,-8,-4,-6,-10,84,72,54,...,3,2,2,6,0,NaN,0.0,8.0,NaN,-1<br />
3,2014-1-4,-1,-2,-3,-4,-5,-6,80,74,64,...,8,4,2,14,2,NaN,0.0,8.0,NaN,-1<br />
4,2014-1-5,-1,-3,-6,-4,-6,-8,93,79,71,...,6,3,2,14,2,NaN,0.0,8.0,Snow,-1<br />
5,2014-1-6,-2,-4,-9,-7,-9,-12,80,67,45,...,10,6,3,14,3,NaN,0.0,8.0,NaN,-1<br />
6,2014-1-7,-4,-7,-9,-10,-11,-12,86,72,48,...,10,6,2,14,6,NaN,0.0,7.0,Snow,30<br />
7,2014-1-8,-5,-7,-11,-9,-10,-12,87,75,65,...,6,4,2,11,5,NaN,0.0,8.0,NaN,-1<br />
8,2014-1-9,-6,-11,-16,-9,-12,-17,100,88,67,...,6,4,1,8,3,NaN,0.0,5.0,Fog,70<br />
9,2014-1-10,-5,-10,-14,-10,-11,-13,95,78,56,...,2,2,2,6,2,NaN,0.0,8.0,Snow,-1<br />

In [ ]:
#checking the data infor
delhi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    object
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            365 non-null    int64
 14   Mean VisibilityKm           365 non-null    int64
 15   Min VisibilitykM            365 non-null    int64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          2 non-null      float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  285 non-null    float64
 21   Events                      92 non-null     object
 22  WindDirDegrees<br />         365 non-null    object
dtypes: float64(3), int64(17), object(3)
memory usage: 65.7+ KB

In [ ]:
#checking the dataset shape
delhi.shape

(365, 23)

In [ ]:
#checking null values
delhi.isna().sum()

Date                             0
Max TemperatureC                 0
Mean TemperatureC                0
Min TemperatureC                 0
Dew PointC                       0
MeanDew PointC                   0
Min DewpointC                    0
Max Humidity                     0
 Mean Humidity                   0
 Min Humidity                    0
 Max Sea Level PressurehPa       0
 Mean Sea Level PressurehPa      0
 Min Sea Level PressurehPa       0
 Max VisibilityKm                0
 Mean VisibilityKm               0
 Min VisibilitykM                0
 Max Wind SpeedKm/h              0
 Mean Wind SpeedKm/h             0
 Max Gust SpeedKm/h            363
Precipitationmm                  0
 CloudCover                     80
 Events                        273
WindDirDegrees<br />             0
dtype: int64

In [ ]:
print(delhi.columns.tolist())

['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']

In [ ]:
delhi.drop([' Max Gust SpeedKm/h'], axis=1, inplace=True)
delhi.head(10)

,Date,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Min Sea Level PressurehPa,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,-4,-7,-9,-9,-10,-11,82,70,58,...,1033,2,2,2,6,2,0.0,8.0,NaN,-1<br />
1,2014-1-2,-1,-4,-8,-6,-8,-11,75,69,53,...,1032,3,2,2,6,0,0.0,8.0,NaN,-1<br />
2,2014-1-3,1,-3,-8,-4,-6,-10,84,72,54,...,1033,3,2,2,6,0,0.0,8.0,NaN,-1<br />
3,2014-1-4,-1,-2,-3,-4,-5,-6,80,74,64,...,1032,8,4,2,14,2,0.0,8.0,NaN,-1<br />
4,2014-1-5,-1,-3,-6,-4,-6,-8,93,79,71,...,1033,6,3,2,14,2,0.0,8.0,Snow,-1<br />
5,2014-1-6,-2,-4,-9,-7,-9,-12,80,67,45,...,1033,10,6,3,14,3,0.0,8.0,NaN,-1<br />
6,2014-1-7,-4,-7,-9,-10,-11,-12,86,72,48,...,1025,10,6,2,14,6,0.0,7.0,Snow,30<br />
7,2014-1-8,-5,-7,-11,-9,-10,-12,87,75,65,...,1032,6,4,2,11,5,0.0,8.0,NaN,-1<br />
8,2014-1-9,-6,-11,-16,-9,-12,-17,100,88,67,...,1022,6,4,1,8,3,0.0,5.0,Fog,70<br />
9,2014-1-10,-5,-10,-14,-10,-11,-13,95,78,56,...,1035,2,2,2,6,2,0.0,8.0,Snow,-1<br />

In [ ]:
#replacing the missing values with ffill and bfill
delhi1 =delhi.ffill().bfill()
delhi1.isna().sum()

Date                           0
Max TemperatureC               0
Mean TemperatureC              0
Min TemperatureC               0
Dew PointC                     0
MeanDew PointC                 0
Min DewpointC                  0
Max Humidity                   0
 Mean Humidity                 0
 Min Humidity                  0
 Max Sea Level PressurehPa     0
 Mean Sea Level PressurehPa    0
 Min Sea Level PressurehPa     0
 Max VisibilityKm              0
 Mean VisibilityKm             0
 Min VisibilitykM              0
 Max Wind SpeedKm/h            0
 Mean Wind SpeedKm/h           0
Precipitationmm                0
 CloudCover                    0
 Events                        0
WindDirDegrees<br />           0
dtype: int64

In [ ]:
#data statistical description
delhi1.describe()

,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,Max Sea Level PressurehPa,Mean Sea Level PressurehPa,Min Sea Level PressurehPa,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Precipitationmm,CloudCover
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,20.200000,13.709589,7.197260,6.443836,3.783562,0.506849,74.813699,50.638356,27.410959,1019.200000,1015.200000,1010.920548,11.575342,9.512329,8.202740,19.265753,5.915068,0.617288,3.536986
std,11.521409,10.060151,8.855339,6.440364,6.511170,6.703950,16.751688,18.401077,18.439264,7.746038,8.261921,9.486355,2.833851,2.098662,3.022351,14.916362,4.449462,1.772568,2.631566
min,-6.000000,-11.000000,-17.000000,-13.000000,-15.000000,-22.000000,30.000000,16.000000,4.000000,1000.000000,997.000000,991.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.000000,6.000000,1.000000,2.000000,-1.000000,-4.000000,60.000000,35.000000,14.000000,1014.000000,1009.000000,1003.000000,10.000000,9.000000,8.000000,11.000000,3.000000,0.000000,1.000000
50%,21.000000,14.000000,8.000000,8.000000,4.000000,1.000000,78.000000,49.000000,21.000000,1017.000000,1014.000000,1010.000000,11.000000,10.000000,10.000000,18.000000,5.000000,0.000000,3.000000
75%,31.000000,23.000000,15.000000,12.000000,9.000000,6.000000,88.000000,65.000000,38.000000,1025.000000,1021.000000,1018.000000,14.000000,11.000000,10.000000,23.000000,6.000000,0.000000,6.000000
max,38.000000,30.000000,23.000000,18.000000,16.000000,13.000000,100.000000,94.000000,84.000000,1042.000000,1036.000000,1035.000000,19.000000,14.000000,10.000000,209.000000,37.000000,11.940000,8.000000

In [ ]:
#importing dataset London_2014.csv
london = pd.read_csv('/content/drive/MyDrive/datasets/London_2014.csv')
london.head(10)

,GMT,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,11,8,6,9,7,4,94,86,73,...,31,11,2,40,26,66.0,9.91,4.0,Rain,186<br />
1,2014-1-2,11,9,6,9,6,4,94,81,60,...,31,15,5,32,21,50.0,1.02,2.0,Rain,214<br />
2,2014-1-3,11,8,6,9,5,2,94,76,54,...,31,12,0,50,29,69.0,7.11,2.0,Rain-Thunderstorm,219<br />
3,2014-1-4,9,6,3,8,6,2,93,85,65,...,31,12,5,35,21,39.0,9.91,4.0,Rain,211<br />
4,2014-1-5,12,7,1,11,4,-1,100,88,77,...,31,14,5,35,16,NaN,0.25,5.0,Rain,199<br />
5,2014-1-6,12,10,8,11,8,6,94,78,60,...,31,12,5,50,29,61.0,2.03,4.0,Rain,219<br />
6,2014-1-7,12,10,8,8,7,6,87,78,63,...,31,13,5,39,27,55.0,5.08,3.0,Rain,219<br />
7,2014-1-8,12,9,7,11,7,6,94,85,69,...,27,14,6,24,18,37.0,1.02,3.0,Rain,197<br />
8,2014-1-9,11,8,5,11,5,2,94,76,53,...,31,13,5,40,26,60.0,0.00,4.0,Rain,247<br />
9,2014-1-10,11,7,2,7,4,2,93,85,66,...,31,17,10,24,13,32.0,0.25,3.0,Rain,216<br />

In [ ]:
#checking the data infor
london.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   GMT                          365 non-null    object
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            365 non-null    int64
 14   Mean VisibilityKm           365 non-null    int64
 15   Min VisibilitykM            365 non-null    int64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          131 non-null    float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  355 non-null    float64
 21   Events                      251 non-null    object
 22  WindDirDegrees<br />         365 non-null    object
dtypes: float64(3), int64(17), object(3)
memory usage: 65.7+ KB

In [ ]:
#checking for the shape of the dataset
london.shape

(365, 23)

In [ ]:
#checking for the null values
london.isna().sum()

GMT                              0
Max TemperatureC                 0
Mean TemperatureC                0
Min TemperatureC                 0
Dew PointC                       0
MeanDew PointC                   0
Min DewpointC                    0
Max Humidity                     0
 Mean Humidity                   0
 Min Humidity                    0
 Max Sea Level PressurehPa       0
 Mean Sea Level PressurehPa      0
 Min Sea Level PressurehPa       0
 Max VisibilityKm                0
 Mean VisibilityKm               0
 Min VisibilitykM                0
 Max Wind SpeedKm/h              0
 Mean Wind SpeedKm/h             0
 Max Gust SpeedKm/h            234
Precipitationmm                  0
 CloudCover                     10
 Events                        114
WindDirDegrees<br />             0
dtype: int64

In [ ]:
#filling the missing values using ffill and bfill
london1 =london.ffill().bfill()
london1.isna().sum()

GMT                            0
Max TemperatureC               0
Mean TemperatureC              0
Min TemperatureC               0
Dew PointC                     0
MeanDew PointC                 0
Min DewpointC                  0
Max Humidity                   0
 Mean Humidity                 0
 Min Humidity                  0
 Max Sea Level PressurehPa     0
 Mean Sea Level PressurehPa    0
 Min Sea Level PressurehPa     0
 Max VisibilityKm              0
 Mean VisibilityKm             0
 Min VisibilitykM              0
 Max Wind SpeedKm/h            0
 Mean Wind SpeedKm/h           0
 Max Gust SpeedKm/h            0
Precipitationmm                0
 CloudCover                    0
 Events                        0
WindDirDegrees<br />           0
dtype: int64

In [ ]:
#describing the statistical data
london1.describe()

,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,Max Sea Level PressurehPa,Mean Sea Level PressurehPa,Min Sea Level PressurehPa,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,16.328767,12.328767,8.293151,10.356164,7.863014,5.241096,93.145205,73.802740,47.019178,1015.980822,1012.386301,1008.994521,28.808219,13.167123,6.183562,25.175342,13.863014,44.767123,1.378356,3.167123
std,5.766174,5.087300,4.773908,3.835096,3.929024,4.177643,5.685267,10.379317,16.107201,9.523087,10.393432,11.424861,4.842740,3.339246,3.255047,9.238414,6.374561,10.525115,3.097608,1.445726
min,4.000000,1.000000,-4.000000,1.000000,-2.000000,-6.000000,71.000000,48.000000,15.000000,987.000000,979.000000,975.000000,6.000000,3.000000,0.000000,8.000000,3.000000,27.000000,0.000000,1.000000
25%,11.000000,8.000000,5.000000,8.000000,4.000000,2.000000,88.000000,66.000000,34.000000,1011.000000,1006.000000,1002.000000,29.000000,11.000000,3.000000,19.000000,10.000000,37.000000,0.000000,2.000000
50%,16.000000,12.000000,8.000000,11.000000,8.000000,5.000000,94.000000,74.000000,45.000000,1016.000000,1013.000000,1011.000000,31.000000,13.000000,6.000000,24.000000,13.000000,45.000000,0.000000,3.000000
75%,21.000000,17.000000,12.000000,13.000000,11.000000,8.000000,100.000000,82.000000,60.000000,1023.000000,1020.000000,1017.000000,31.000000,15.000000,10.000000,29.000000,16.000000,50.000000,1.020000,4.000000
max,30.000000,24.000000,19.000000,19.000000,17.000000,15.000000,100.000000,96.000000,92.000000,1043.000000,1041.000000,1038.000000,31.000000,24.000000,10.000000,66.000000,47.000000,90.000000,21.080000,7.000000

In [ ]:
min_temp = london1['Min TemperatureC'].min()
print(min_temp)

-4

In [ ]:
max_temp = london1['Max TemperatureC'].max()
print(max_temp)

30

In [ ]:
#importing dataset Moscow_SVO_2014.csv
moscow = pd.read_csv('/content/drive/MyDrive/datasets/Moscow_SVO_2014.csv')
moscow.head(10)

,Date,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,1,-1,-2,-2,-3,-5,87,81,75,...,10.0,10.0,10.0,21,14,NaN,0.0,8.0,NaN,227<br />
1,2014-1-2,-2,-3,-5,-4,-5,-6,93,87,80,...,10.0,10.0,10.0,18,13,NaN,0.0,8.0,NaN,200<br />
2,2014-1-3,-1,-3,-4,-2,-4,-6,100,89,80,...,10.0,7.0,3.0,21,11,32.0,0.0,8.0,Snow,134<br />
3,2014-1-4,-1,-2,-2,-3,-4,-5,93,85,80,...,10.0,6.0,3.0,18,13,32.0,0.0,8.0,Snow,157<br />
4,2014-1-5,1,0,-1,1,-1,-3,100,93,81,...,10.0,6.0,1.0,26,16,NaN,0.0,8.0,Snow,195<br />
5,2014-1-6,1,0,0,1,0,-1,100,95,93,...,10.0,3.0,0.0,14,8,26.0,0.0,8.0,Fog-Snow,130<br />
6,2014-1-7,2,1,0,1,1,0,100,100,93,...,5.0,2.0,0.0,14,11,NaN,0.0,8.0,Fog,124<br />
7,2014-1-8,3,2,1,2,2,1,100,98,93,...,10.0,6.0,3.0,29,19,40.0,0.0,8.0,Rain-Snow,211<br />
8,2014-1-9,3,2,2,2,2,1,100,98,93,...,10.0,3.0,0.0,21,16,NaN,0.0,8.0,Fog-Rain,225<br />
9,2014-1-10,4,2,2,3,2,1,100,94,87,...,10.0,9.0,3.0,26,18,40.0,0.0,8.0,Rain,184<br />

In [ ]:
#checking the data infor
moscow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         365 non-null    object
 1   Max TemperatureC             365 non-null    int64
 2   Mean TemperatureC            365 non-null    int64
 3   Min TemperatureC             365 non-null    int64
 4   Dew PointC                   365 non-null    int64
 5   MeanDew PointC               365 non-null    int64
 6   Min DewpointC                365 non-null    int64
 7   Max Humidity                 365 non-null    int64
 8    Mean Humidity               365 non-null    int64
 9    Min Humidity                365 non-null    int64
 10   Max Sea Level PressurehPa   365 non-null    int64
 11   Mean Sea Level PressurehPa  365 non-null    int64
 12   Min Sea Level PressurehPa   365 non-null    int64
 13   Max VisibilityKm            333 non-null    float64
 14   Mean VisibilityKm           333 non-null    float64
 15   Min VisibilitykM            333 non-null    float64
 16   Max Wind SpeedKm/h          365 non-null    int64
 17   Mean Wind SpeedKm/h         365 non-null    int64
 18   Max Gust SpeedKm/h          213 non-null    float64
 19  Precipitationmm              365 non-null    float64
 20   CloudCover                  333 non-null    float64
 21   Events                      216 non-null    object
 22  WindDirDegrees<br />         365 non-null    object
dtypes: float64(6), int64(14), object(3)
memory usage: 65.7+ KB

In [ ]:
#checking for missing values in the dataset
moscow.isna().sum()

Date                             0
Max TemperatureC                 0
Mean TemperatureC                0
Min TemperatureC                 0
Dew PointC                       0
MeanDew PointC                   0
Min DewpointC                    0
Max Humidity                     0
 Mean Humidity                   0
 Min Humidity                    0
 Max Sea Level PressurehPa       0
 Mean Sea Level PressurehPa      0
 Min Sea Level PressurehPa       0
 Max VisibilityKm               32
 Mean VisibilityKm              32
 Min VisibilitykM               32
 Max Wind SpeedKm/h              0
 Mean Wind SpeedKm/h             0
 Max Gust SpeedKm/h            152
Precipitationmm                  0
 CloudCover                     32
 Events                        149
WindDirDegrees<br />             0
dtype: int64

In [ ]:
#using the foward and backward fill to fill the missing values
moscow_data =  brasilia.ffill().bfill()
#rconfirming the missing data
moscow_data.isna().sum()

Date                           0
Max TemperatureC               0
Mean TemperatureC              0
Min TemperatureC               0
Dew PointC                     0
MeanDew PointC                 0
Min DewpointC                  0
Max Humidity                   0
 Mean Humidity                 0
 Min Humidity                  0
 Max Sea Level PressurehPa     0
 Mean Sea Level PressurehPa    0
 Min Sea Level PressurehPa     0
 Max VisibilityKm              0
 Mean VisibilityKm             0
 Min VisibilitykM              0
 Max Wind SpeedKm/h            0
 Mean Wind SpeedKm/h           0
 Max Gust SpeedKm/h            0
Precipitationmm                0
 CloudCover                    0
 Events                        0
WindDirDegrees<br />           0
dtype: int64

In [ ]:
#claculating the statistical data information
moscow_data.describe()

,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,Max Sea Level PressurehPa,Mean Sea Level PressurehPa,Min Sea Level PressurehPa,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,28.284932,22.895890,17.726027,15.813699,13.676712,10.558904,79.504110,58.068493,29.780822,1021.410959,1019.219178,1017.016438,18.975342,12.265753,8.780822,22.364384,7.632877,42.175342,2.059315,3.372603
std,2.324243,2.035431,2.702564,3.496203,3.896974,4.949188,11.356758,13.868821,14.187952,2.347758,2.333738,2.523462,0.471082,2.459128,4.389193,11.227730,2.659632,8.172383,6.186198,1.403808
min,19.000000,16.000000,9.000000,6.000000,3.000000,-5.000000,47.000000,26.000000,6.000000,1015.000000,1014.000000,1012.000000,10.000000,7.000000,0.000000,10.000000,3.000000,26.000000,0.000000,1.000000
25%,27.000000,21.000000,16.000000,13.000000,11.000000,7.000000,73.000000,49.000000,19.000000,1020.000000,1018.000000,1015.000000,19.000000,11.000000,6.000000,19.000000,6.000000,35.000000,0.000000,2.000000
50%,28.000000,23.000000,18.000000,17.000000,14.000000,11.000000,83.000000,58.000000,27.000000,1021.000000,1019.000000,1017.000000,19.000000,12.000000,10.000000,21.000000,8.000000,40.000000,0.000000,3.000000
75%,29.000000,24.000000,20.000000,19.000000,17.000000,15.000000,88.000000,70.000000,39.000000,1023.000000,1020.000000,1018.000000,19.000000,13.000000,10.000000,24.000000,10.000000,47.000000,0.760000,5.000000
max,36.000000,28.000000,23.000000,22.000000,19.000000,18.000000,100.000000,88.000000,73.000000,1028.000000,1026.000000,1025.000000,19.000000,19.000000,19.000000,195.000000,19.000000,66.000000,57.910000,7.000000

In [ ]:
#checking the shape of the dataset
moscow_data.shape

(365, 23)

In [ ]:
#checking temperatures on moscow data days that had min temperatures
min_temp = moscow_data['Min TemperatureC'].min()
print(min_temp)

9

In [ ]:
#checking temperatures on moscow data days that had max temperatures
max_temp = moscow_data['Max TemperatureC'].max()
print(max_temp)

36

link to my publication: https://datacleaning.hashnode.dev/turning-weather-data-into-stories-what-six-global-cities-taught-me-about-climate-and-data-analysis