<a href="https://colab.research.google.com/github/Jess-chege/Data-Science-projects/blob/main/test2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Question 1
1. How will you create an empty Dataframe in python?

In [ ]:
#creating an empty Dataframe
import pandas as pd

data = pd.DataFrame()
print(data)

Empty DataFrame
Columns: []
Index: []

### Question 2
How do you drop the column "Skin_Fold" from a DataFrame (Diabetes
Data.csv)? Provide a code snippet and explain any parameters used.

In [ ]:
#importing data
data1 = pd.read_csv("Diabetes Data.csv")
data1.head(10)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
7,10,115.0,NaN,NaN,NaN,35.3,0.134,29,0
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
9,8,125.0,96.0,NaN,NaN,NaN,0.232,54,1

In [ ]:
#dropping Skin_Fold column from the data
data2 = data1.drop("Skin_Fold", axis = 1) #when dropping a column we use the drop function and the axis = 1
data2.head(10)

,Pregnant,Glucose,Diastolic_BP,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,23.3,0.672,32,1
3,1,89.0,66.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,NaN,25.6,0.201,30,0
6,3,78.0,50.0,88.0,31.0,0.248,26,1
7,10,115.0,NaN,NaN,35.3,0.134,29,0
8,2,197.0,70.0,543.0,30.5,0.158,53,1
9,8,125.0,96.0,NaN,NaN,0.232,54,1

### Question 3
How will you add a scalar column with same value for all rows to a
pandas DataFrame?Using insert function and assigning a scalar value to a new  column as shown below

In [ ]:
#adding a scalar column with same value for all rows in pandas using the insert function

data2.insert(0,'patients',34.5)

data2.head(10)

,patients,Pregnant,Glucose,Diastolic_BP,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,34.5,6,148.0,72.0,NaN,33.6,0.627,50,1
1,34.5,1,85.0,66.0,NaN,26.6,0.351,31,0
2,34.5,8,183.0,64.0,NaN,23.3,0.672,32,1
3,34.5,1,89.0,66.0,94.0,28.1,0.167,21,0
4,34.5,0,137.0,40.0,168.0,43.1,2.288,33,1
5,34.5,5,116.0,74.0,NaN,25.6,0.201,30,0
6,34.5,3,78.0,50.0,88.0,31.0,0.248,26,1
7,34.5,10,115.0,NaN,NaN,35.3,0.134,29,0
8,34.5,2,197.0,70.0,543.0,30.5,0.158,53,1
9,34.5,8,125.0,96.0,NaN,NaN,0.232,54,1

### Question 4
4. How will you retrieve a single column from pandas DataFrame? by assigning a value and calling the specific column

In [ ]:
#Retrieving a single column from pandas
Ages = data2["Age"]

Ages.head(10)

0    50
1    31
2    32
3    21
4    33
5    30
6    26
7    29
8    53
9    54
Name: Age, dtype: int64

### Question 5
5. How will you rename a column'Class' to Target in a dataframe (Diabetes
Data.csv)? Provide a code snippet and explain any parameters used.

In [ ]:
#renaming a column in the data set using the rename function
Data5 = data2.rename(columns = {'Class': 'Target'})
Data5.head(10)

,patients,Pregnant,Glucose,Diastolic_BP,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Target
0,34.5,6,148.0,72.0,NaN,33.6,0.627,50,1
1,34.5,1,85.0,66.0,NaN,26.6,0.351,31,0
2,34.5,8,183.0,64.0,NaN,23.3,0.672,32,1
3,34.5,1,89.0,66.0,94.0,28.1,0.167,21,0
4,34.5,0,137.0,40.0,168.0,43.1,2.288,33,1
5,34.5,5,116.0,74.0,NaN,25.6,0.201,30,0
6,34.5,3,78.0,50.0,88.0,31.0,0.248,26,1
7,34.5,10,115.0,NaN,NaN,35.3,0.134,29,0
8,34.5,2,197.0,70.0,543.0,30.5,0.158,53,1
9,34.5,8,125.0,96.0,NaN,NaN,0.232,54,1

### QUESTION 6
6. How can we select a column in pandas DataFrame?

In [ ]:
#selecting a column in pandas
Diastolic_Bp = data2['Diastolic_BP']
Diastolic_Bp.head(10)

0    72.0
1    66.0
2    64.0
3    66.0
4    40.0
5    74.0
6    50.0
7     NaN
8    70.0
9    96.0
Name: Diastolic_BP, dtype: float64

### QUESTION 7
7. How can we retrieve a row in pandas DataFrame?

In [ ]:
#retrieving row
row = data2.loc[8]
row

patients              34.500
Pregnant               2.000
Glucose              197.000
Diastolic_BP          70.000
Serum_Insulin        543.000
BMI                   30.500
Diabetes_Pedigree      0.158
Age                   53.000
Class                  1.000
Name: 8, dtype: float64

### QUESTION 8
8. How will you append new rows to a pandas DataFrame?

In [ ]:
#append function is used to add new rows to a dataframe and I was not able to get ouput for this cell since pandas Iam using doesn't support append function

#new_row =pd.DataFrame({'patients':[34.5],'Pregnant':[3],'Glucose':[198],'Diastolic_BP':[78],'Serum_Insulin':[86],'BMI':[30.5],'Diabetes_Pedigree':[0.15],'Age':[45],'Class':[1]})

#df = data2.append(new_row, ignore_index=True)

#df.head()

### Question 9
9. How will you delete rows from a pandas DataFrame (Diabetes Data.csv)?
Delete row number 713 and provide a code snippet showing the deleted

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patients           768 non-null    float64
 1   Pregnant           768 non-null    int64
 2   Glucose            763 non-null    float64
 3   Diastolic_BP       733 non-null    float64
 4   Serum_Insulin      394 non-null    float64
 5   BMI                757 non-null    float64
 6   Diabetes_Pedigree  768 non-null    float64
 7   Age                768 non-null    int64
 8   Class              768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [ ]:
#deleting rows from pandas Dataframe entries changed from 768 to 767 after dropping row 713
df1 = data2.drop(713, axis=0)

df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 767 entries, 0 to 767
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patients           767 non-null    float64
 1   Pregnant           767 non-null    int64
 2   Glucose            762 non-null    float64
 3   Diastolic_BP       732 non-null    float64
 4   Serum_Insulin      393 non-null    float64
 5   BMI                756 non-null    float64
 6   Diabetes_Pedigree  767 non-null    float64
 7   Age                767 non-null    int64
 8   Class              767 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 59.9 KB

### Question 10
10.How will you get the number of rows and columns of a DataFrame in
pandas? Use dataset (Diabetes Data.csv) file and provide a code snippet.

In [ ]:
#how to get number of rows and columns in a dataframe in pandas. we have 768 rows and 9 columns when we use the data.shape
data2.shape

(768, 9)

### Question 11
11.How will you get the top 2 rows from a DataFrame in pandas? Use
dataset (Diabetes Data.csv) file and provide a code snippet.

In [ ]:
# using the iloc function to get 2 first rows in our dataset setting the 0:2
rows = data2.iloc[0:2]
rows

,patients,Pregnant,Glucose,Diastolic_BP,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,34.5,6,148.0,72.0,NaN,33.6,0.627,50,1
1,34.5,1,85.0,66.0,NaN,26.6,0.351,31,0

### Question 12
12.How will you get the last 2 rows from a DataFrame in pandas? Use
dataset (Diabetes Data.csv) file and provide a code snippet.

In [ ]:
#showing the last two rows using the iloc function
last_rows = data2.iloc[766:768]
last_rows

,patients,Pregnant,Glucose,Diastolic_BP,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
766,34.5,1,126.0,60.0,NaN,30.1,0.349,47,1
767,34.5,1,93.0,70.0,NaN,30.4,0.315,23,0

### Question 13
13.How will you get the number of elements in a DataFrame in pandas?

In [ ]:
# getting elements in a dataframe

### Question 14
14.How will you get the names of columns of a DataFrame in pandas? Use
dataset (Diabetes Data.csv) file and provide a code snippet.

In [ ]:
#we use the size function to check the size of the dataset
data2.size

6912

### Question 15
15.How will you convert a DataFrame to an array in pandas?

In [ ]:
#converting the dataframe to array using the to_numpy function
df3 = data2.to_numpy
df3

<bound method DataFrame.to_numpy of      patients  Pregnant  Glucose  Diastolic_BP  Serum_Insulin   BMI  \
0        34.5         6    148.0          72.0            NaN  33.6
1        34.5         1     85.0          66.0            NaN  26.6
2        34.5         8    183.0          64.0            NaN  23.3
3        34.5         1     89.0          66.0           94.0  28.1
4        34.5         0    137.0          40.0          168.0  43.1
..        ...       ...      ...           ...            ...   ...
763      34.5        10    101.0          76.0          180.0  32.9
764      34.5         2    122.0          70.0            NaN  36.8
765      34.5         5    121.0          72.0          112.0  26.2
766      34.5         1    126.0          60.0            NaN  30.1
767      34.5         1     93.0          70.0            NaN  30.4

     Diabetes_Pedigree  Age  Class
0                0.627   50      1
1                0.351   31      0
2                0.672   32      1
3                0.167   21      0
4                2.288   33      1
..                 ...  ...    ...
763              0.171   63      0
764              0.340   27      0
765              0.245   30      0
766              0.349   47      1
767              0.315   23      0

[768 rows x 9 columns]>

### Question 16
16.How can you check if a DataFrame is empty in pandas?

In [ ]:
#checking if a dataframe is empty in pandas using the we print the data set and get empty dataframe as the result
data = pd.DataFrame()
print(data)

Empty DataFrame
Columns: []
Index: []

### Question 17
17.How can you get the sum of values of a pregnant column ? Use dataset
(Diabetes Data.csv) file and provide a code snippet.

In [ ]:
data3 = pd.DataFrame(data2)#converting back the dataset to dataframe from array
data3.head()

#getting sum of values of a pregnant column
Sum_Pregnant = data2['Pregnant'].sum()
print("Sum of column Pregnant:",Sum_Pregnant)

Sum of column Pregnant: 2953

### Question 18
18.How will you get the average of values of a column in pandas
DataFrame?

In [ ]:
#using the mean function  function
Average_Pregnant = data2['Pregnant'].mean()

print("Average of column Pregnant:", Average_Pregnant )

Average of column Pregnant: 3.8450520833333335

### Question 19
19. How can we get the statistical summary of data in a pandas DataFrame?
Use dataset (Diabetes Data.csv) file and provide a code snippet.

In [ ]:
#using the describe function we get the statistical summary
data3.describe()

,patients,Pregnant,Glucose,Diastolic_BP,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
count,768.0,768.000000,763.000000,733.000000,394.000000,757.000000,768.000000,768.000000,768.000000
mean,34.5,3.845052,121.686763,72.405184,155.548223,32.457464,0.471876,33.240885,0.348958
std,0.0,3.369578,30.535641,12.382158,118.775855,6.924988,0.331329,11.760232,0.476951
min,34.5,0.000000,44.000000,24.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,34.5,1.000000,99.000000,64.000000,76.250000,27.500000,0.243750,24.000000,0.000000
50%,34.5,3.000000,117.000000,72.000000,125.000000,32.300000,0.372500,29.000000,0.000000
75%,34.5,6.000000,141.000000,80.000000,190.000000,36.600000,0.626250,41.000000,1.000000
max,34.5,17.000000,199.000000,122.000000,846.000000,67.100000,2.420000,81.000000,1.000000

### Question 20
20.How will you check for the datatypes of a specific column in a
dataframe? Use dataset (Diabetes Data.csv) file and provide a code
snippet.

In [ ]:
#we check data type of a specific column by using the .dtype
data_type = data3['Serum_Insulin'].dtype
print("this is the data type of Serum_Insulin:", data_type)

this is the data type of Serum_Insulin: float64

### Question 21
21.How will you apply a function to a row of pandas DataFrame?

In [ ]:
def count():
    return data1['Glucose']

count()

0      148.0
1       85.0
2      183.0
3       89.0
4      137.0
       ...
763    101.0
764    122.0
765    121.0
766    126.0
767     93.0
Name: Glucose, Length: 768, dtype: float64

### Question 22
22.How can you replace all missing values in a DataFrame bfill and ffill
method? Use dataset (Diabetes Data.csv) file and provide a code snippet.

In [ ]:
#checking for null values
data3.isnull().sum()

patients               0
Pregnant               0
Glucose                5
Diastolic_BP          35
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [ ]:
#using the backward fill and forward fill to fill all null values
data4 = data3.ffill().bfill()
data4.isnull().sum()

patients             0
Pregnant             0
Glucose              0
Diastolic_BP         0
Serum_Insulin        0
BMI                  0
Diabetes_Pedigree    0
Age                  0
Class                0
dtype: int64

### Question 23
23.What is reindexing in pandas?

Invovles changing row labels and column labels of a DataFrame.

### Question 24
24.How write few columns to a file?

In [ ]:
#adding data to an excel file
data2.to_excel('data2.xlsx', sheet_name='Sheet1', index=False)

### Question 25
25.How can you replace all missing values in a DataFrame with the mean of the respective columns? Use dataset (Diabetes Data.csv) file and provide a code snippet.

In [ ]:
#replacing null values using mean
data1.isnull().sum() #checking null values

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [ ]:
#replacing null value using mean
data1.fillna(data1.mean(), inplace=True)
data1.isnull().sum()

Pregnant             0
Glucose              0
Diastolic_BP         0
Skin_Fold            0
Serum_Insulin        0
BMI                  0
Diabetes_Pedigree    0
Age                  0
Class                0
dtype: int64